import { supabase } from '../../../supabaseClient';
import { fetchDemTerrainProfile, type DemTerrainProfile } from '../../../services/demService';
import { getCachedNdviAnomaly } from '../../satellite/services/ndviAnomaly.service';
import type { FrostEventRecord, FrostPocketCell, FrostPocketSnapshot } from '../types/frostPocket';
function text(v:unknown){return String(v??'').trim()} function finite(v:unknown){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
function day(v:unknown){const s=text(v).slice(0,10);return /^\d{4}-\d{2}-\d{2}$/.test(s)?s:null}
export function buildFrostPocketCells(profile:DemTerrainProfile):FrostPocketCell[]{
 const min=profile.stats.minElevationM; const max=profile.stats.maxElevationM; const relief=min!=null&&max!=null?Math.max(0,max-min):0;
 const highBand=Math.max(1,Math.min(4,relief*0.25)); const mediumBand=Math.max(2,Math.min(8,relief*0.5));
 return profile.cells.map(cell=>{const rel=cell.elevationM!=null&&min!=null?cell.elevationM-min:null;const slope=cell.slopeDeg;
  let susceptibility:'low'|'medium'|'high'='low';
  if(rel!=null&&rel<=highBand&&(slope==null||slope<=5)) susceptibility='high'; else if(rel!=null&&rel<=mediumBand&&(slope==null||slope<=10)) susceptibility='medium';
  return {...cell,relativeElevationM:rel==null?null:Number(rel.toFixed(1)),susceptibility}; });
}
function mapEvent(row:any):FrostEventRecord{return{id:String(row.id),fieldId:String(row.field_id),eventDate:String(row.event_date),observedMinTempC:finite(row.observed_min_temp_c),source:row.source==='sensor'?'sensor':row.source==='weather_station'?'weather_station':'user',notes:text(row.notes)||null,createdAt:String(row.created_at??new Date().toISOString())}}
export function buildFrostPocketSnapshot(input:{fieldId:string;crop?:string|null;profile:DemTerrainProfile;forecastMinC?:number|null;latestEvent?:FrostEventRecord|null;now?:Date}):FrostPocketSnapshot{
 const cells=buildFrostPocketCells(input.profile); const high=cells.filter(c=>c.susceptibility==='high').length; const medium=cells.filter(c=>c.susceptibility==='medium').length; const minC=finite(input.forecastMinC);
 const frostSignal=minC==null?'none':minC<=0?'frost':minC<=2?'watch':'none'; const anomaly=getCachedNdviAnomaly(input.fieldId); const eventDay=input.latestEvent?.eventDate??null;
 let post:FrostPocketSnapshot['postEventSatellite']={status:'unavailable',latestDate:anomaly?.latestDate??null,deviation:finite(anomaly?.deviation),note:'Don olayı sonrası kullanılabilir NDVI karşılaştırması yok.'};
 if(eventDay&&anomaly?.quality==='usable'&&anomaly.latestDate&&anomaly.latestDate>eventDay){ if(anomaly.anomaly&&anomaly.direction==='negative') post={status:'negative_change_after_event',latestDate:anomaly.latestDate,deviation:finite(anomaly.deviation),note:'Don olayından sonraki uydu gözleminde negatif NDVI değişim sinyali var. Bu zaman ilişkisi don hasarını tek başına kanıtlamaz.'}; else post={status:'no_negative_signal',latestDate:anomaly.latestDate,deviation:finite(anomaly.deviation),note:'Don olayından sonraki kullanılabilir uydu gözleminde belirgin negatif NDVI anomali sinyali yok.'}; }
 const evidence=[`DEM: Copernicus GLO-90, yaklaşık ${input.profile.resolutionMeters} m.`,high?`${high} grid hücresi göreli alçak/düşük eğimli topografik don cebi adayı.`:'Belirgin yüksek hassasiyetli topoğrafik cep ayrılmadı.',minC!=null?`Kısa vadeli minimum sıcaklık ${minC.toFixed(1)} °C.`:'',input.latestEvent?`Kayıtlı son don olayı ${input.latestEvent.eventDate}${input.latestEvent.observedMinTempC!=null?` · ${input.latestEvent.observedMinTempC.toFixed(1)} °C`:''}.`:'',post.status==='negative_change_after_event'?post.note:''].filter(Boolean);
 return{version:'20.0',fieldId:input.fieldId,crop:text(input.crop)||null,status:'ready',terrain:{source:'Copernicus DEM GLO-90',resolutionMeters:90,reliefM:input.profile.stats.reliefM,cells,highPocketCount:high,mediumPocketCount:medium},forecast:{minTemperatureC:minC,frostSignal},latestEvent:input.latestEvent??null,postEventSatellite:post,evidence,guardrails:['dem-pocket-is-topographic-susceptibility-not-measured-temperature','90m-dem-is-not-microtopographic-survey','forecast-frost-is-not-damage','post-event-ndvi-change-is-not-causal-proof','field-observation-required-for-damage-confirmation'],generatedAt:(input.now??new Date()).toISOString()};
}
export async function loadFrostPocketSnapshot(fieldIdInput:string,forecastMinC?:number|null){const fieldId=text(fieldIdInput);if(!fieldId)throw new Error('Don cebi için tarla seçilemedi.');const{data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error('Don cebi için oturum gerekli.');const{data:field,error}=await supabase.from('fields').select('id,crop,latitude,longitude,parcel_centroid_lat,parcel_centroid_lng').eq('id',fieldId).eq('user_id',auth.user.id).maybeSingle();if(error)throw error;if(!field)throw new Error('Tarla bulunamadı.');const lat=finite(field.parcel_centroid_lat)??finite(field.latitude);const lon=finite(field.parcel_centroid_lng)??finite(field.longitude);if(lat==null||lon==null)throw new Error('Don cebi için tarla koordinatı gerekli.');const [profile,eventRes]=await Promise.all([fetchDemTerrainProfile(lat,lon,{gridSize:9,stepMeters:90}),supabase.from('field_frost_events').select('*').eq('user_id',auth.user.id).eq('field_id',fieldId).order('event_date',{ascending:false}).limit(1).maybeSingle()]);const event=eventRes.error?.code==='42P01'?null:eventRes.data?mapEvent(eventRes.data):null;return buildFrostPocketSnapshot({fieldId,crop:field.crop,profile,forecastMinC,latestEvent:event});}
export async function recordFrostEvent(input:{fieldId:string;eventDate:string;observedMinTempC?:number|null;source?:FrostEventRecord['source'];notes?:string|null}){const{data:auth,error:authError}=await supabase.auth.getUser();if(authError||!auth.user)throw new Error('Don olayı kaydı için oturum gerekli.');const{data,error}=await supabase.from('field_frost_events').insert({user_id:auth.user.id,field_id:text(input.fieldId),event_date:day(input.eventDate),observed_min_temp_c:finite(input.observedMinTempC),source:input.source??'user',notes:text(input.notes)||null}).select('*').single();if(error)throw error;if(typeof window!=='undefined')window.dispatchEvent(new CustomEvent('tp:frost-event-updated',{detail:{fieldId:text(input.fieldId)}}));return mapEvent(data)}
