import { useMemo, useState } from 'react';
import { knowledgeSources } from '../data/sources.ts';
import { knowledgeEntries } from '../services/catalog.ts';
import './KnowledgeLibrary.css';

const GUIDE = [
 {id:'ndvi',category:'Uydu ve Tarım Teknolojisi',title:'NDVI Nedir, Nasıl Yorumlanır?',summary:'Bitki örtüsündeki mekânsal ve zamansal değişimi uydu görüntülerinden izlemeye yardımcı olan vejetasyon indeksi.',sections:[['Tek başına teşhis değildir','NDVI değişimi hastalık, su stresi, beslenme, gelişim dönemi, toprak arka planı veya hasat gibi farklı nedenlerden oluşabilir. Hava, fenoloji ve saha gözlemleriyle birlikte değerlendirilmelidir.']]},
 {id:'ph',category:'Toprak',title:'Toprak pH Değeri Ne Anlama Gelir?',summary:'Toprağın asitlik ve alkalilik durumunun besin alınabilirliğiyle ilişkisi.',sections:[['Neden önemli?','pH besin elementlerinin alınabilirliğini ve topraktaki biyolojik süreçleri etkiler. Kesin karar için uygun yöntemle alınmış laboratuvar analizi esas alınmalıdır.']]},
 {id:'organic',category:'Toprak',title:'Toprak Organik Maddesi',summary:'Organik maddenin toprak yapısı, su tutma ve besin döngüsündeki rolü.',sections:[['Görevi','Organik madde agregat yapısını, su tutma kapasitesini, biyolojik faaliyeti ve besin döngüsünü destekler. Sonuçlar toprak bünyesi ve yerel koşullarla birlikte değerlendirilmelidir.']]},
 {id:'nitrogen',category:'Bitki Besleme',title:'Azot: Bitkide Görevi ve Eksiklik Şüphesi',summary:'Azotun büyüme ve klorofil oluşumundaki rolü ile gözlenebilen işaretler.',sections:[['Dikkat','Yaprak rengi tek başına azot eksikliğini kanıtlamaz. Su stresi, kök sorunu ve başka beslenme sorunları benzer belirti oluşturabilir. Fotoğraftan kesin azot miktarı belirlenemez.']]},
 {id:'irrigation',category:'Sulama',title:'Sulama Zamanı Nasıl Belirlenir?',summary:'Hava, toprak, ürün dönemi ve kök bölgesini birlikte değerlendirme.',sections:[['Tek veri yeterli değildir','Sulama zamanı; yağış, evapotranspirasyon, kök bölgesi su durumu, toprağın su tutma kapasitesi, ürünün gelişim dönemi ve son sulama kaydı birlikte değerlendirilerek belirlenir.']]},
 {id:'et',category:'Sulama',title:'Evapotranspirasyon (ET) Nedir?',summary:'Toprak yüzeyinden buharlaşma ve bitkiden terleme yoluyla gerçekleşen toplam su kaybı.',sections:[['ET0 ve ETc','Referans evapotranspirasyon atmosferik su talebini temsil eder. Ürün su tüketimi değerlendirmesinde ürün ve gelişim dönemi gibi ek bilgiler gerekir.']]},
 {id:'sampling',category:'Tarla İşlemleri',title:'Toprak Örneği Nasıl Alınır?',summary:'Laboratuvar sonucunun tarlayı temsil etmesi için doğru örnekleme yaklaşımı.',sections:[['Temsil edici örnek','Benzer özellikteki bölümden birden fazla noktadan alt örnek alınarak karıştırılır. Yol kenarı, yığın ve su birikintisi gibi sıra dışı noktalar genel örneğe dahil edilmemelidir.']]},
 {id:'scouting',category:'Hastalık ve Zararlılar',title:'Tarla Gözlemi Nasıl Yapılır?',summary:'Sorunu erken fark etmek için düzenli ve kayıtlı tarla kontrolünün temelleri.',sections:[['Düzenli izleme','Tarla farklı bölgeleri temsil edecek biçimde gezilmeli; yaprak, gövde, kök ve ürün belirtileri incelenmeli; fotoğraf, tarih ve konum kaydedilmelidir.']]},
 {id:'ipm',category:'Hastalık ve Zararlılar',title:'Entegre Mücadele Nedir?',summary:'Gözlem, kültürel ve biyolojik yöntemleri birlikte ele alan yaklaşım.',sections:[['Temel yaklaşım','Doğru teşhis, düzenli izleme ve uygun yöntemin doğru zamanda seçilmesi esastır. Yerel eşikler ve resmî tavsiyeler dikkate alınmalıdır.']]},
 {id:'phenology',category:'Bitkisel Üretim',title:'Fenoloji: Bitkinin Gelişim Dönemini Bilmek',summary:'Ekim, çıkış, vejetatif gelişim, çiçeklenme ve olgunlaşma dönemlerinin kararlarla ilişkisi.',sections:[['Neden önemli?','Bitkinin su ve besin ihtiyacı ile bazı riskler gelişim dönemine göre değişir. Takvim tarihi tek başına gelişim dönemini kesin olarak göstermez.']]},
 {id:'salinity',category:'Toprak',title:'Toprak Tuzluluğu Nedir?',summary:'Çözünmüş tuzların bitki su alımı ve gelişimi üzerindeki etkisine giriş.',sections:[['Ölçüm önemlidir','Tuzluluk bitkinin su almasını zorlaştırabilir. Kesin değerlendirme için uygun toprak veya sulama suyu analizindeki elektriksel iletkenlik gibi ölçümler kullanılmalıdır.']]},
 {id:'compaction',category:'Toprak',title:'Toprak Sıkışması ve Kök Gelişimi',summary:'Sıkışmış tabakaların köklenme, su hareketi ve havalanma üzerindeki olası etkileri.',sections:[['Saha işaretleri','Köklerin belirli derinlikte yön değiştirmesi, suyun yüzeyde kalması ve teker izlerinde gelişim farkları sıkışma şüphesi oluşturabilir. Tek belirti kesin teşhis değildir.']]},
 {id:'infiltration',category:'Toprak',title:'Su İnfiltrasyonu Nedir?',summary:'Yağış veya sulama suyunun toprak yüzeyinden profile girişini anlamak.',sections:[['Neyi etkiler?','Toprak yapısı, yüzey kabuklaşması, sıkışma, organik madde, bitki örtüsü ve başlangıç nemi suyun toprağa giriş hızını etkileyebilir.']]},
 {id:'erosion',category:'Toprak',title:'Su ve Rüzgâr Erozyonu',summary:'Verimli üst toprağın taşınmasına yol açan süreçleri tanıma.',sections:[['Saha işaretleri','Yüzey akış izleri, küçük yarıntılar, sediment birikimi veya rüzgârla taşınan ince toprak erozyon riskine işaret edebilir.']]},
 {id:'cover',category:'Toprak Sağlığı',title:'Örtü Bitkileri ve Toprak Sağlığı',summary:'Toprağın çıplak kaldığı dönemleri azaltmaya yönelik koruyucu tarım yaklaşımı.',sections:[['Planlama','Örtü bitkisi seçimi iklim, toprak, ana ürün, su durumu ve yönetim hedefine göre yapılmalıdır. Her tür her üretim sistemine uygun değildir.']]}
] as const;
const categories=[...new Set(GUIDE.map(x=>x.category))];
export default function KnowledgeLibrary(){const[q,setQ]=useState('');const[cat,setCat]=useState('Tümü');const[selected,setSelected]=useState<string|null>(null);const labels=knowledgeEntries.filter(e=>e.contentType==='label');const items=useMemo(()=>{const n=q.trim().toLocaleLowerCase('tr-TR');return GUIDE.filter(x=>(cat==='Tümü'||x.category===cat)&&(!n||`${x.title} ${x.summary} ${x.category}`.toLocaleLowerCase('tr-TR').includes(n)))},[q,cat]);const item=GUIDE.find(x=>x.id===selected);return <section className="tp-knowledge" aria-labelledby="knowledge-heading"><header><p className="tp-knowledge-eyebrow">BİLGİ REHBERİ</p><h1 id="knowledge-heading">Türkçe bilgi kütüphanesi</h1><p>Tarla, bitki, toprak, sulama ve tarım teknolojilerini anlaşılır Türkçe ile keşfet.</p></header><div className="tp-knowledge-filters"><label className="tp-knowledge-search">Bilgi ara<input type="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Örn. azot, NDVI, sulama, pH…"/></label><label>Konu<select value={cat} onChange={e=>setCat(e.target.value)}><option>Tümü</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div><p role="status" className="tp-knowledge-count">{items.length} rehber konusu</p>{item?<article className="tp-knowledge-detail"><button type="button" onClick={()=>setSelected(null)}>‹ Bilgi Kütüphanesine Dön</button><small>{item.category}</small><h2>{item.title}</h2><p>{item.summary}</p>{item.sections.map(s=><section key={s[0]}><h3>{s[0]}</h3><p>{s[1]}</p></section>)}<aside><p>Genel bilgilendirme amaçlıdır. Kesin teşhis, doz veya reçete değildir; tarla uygulamalarında analiz, yerel koşullar, yürürlükteki resmî bilgiler ve gerektiğinde yetkili uzman değerlendirmesi esas alınmalıdır.</p></aside></article>:<div className="tp-knowledge-grid">{items.map(x=><article key={x.id}><span className="tp-knowledge-badge">{x.category} · Rehber</span><h2>{x.title}</h2><p>{x.summary}</p><button type="button" onClick={()=>setSelected(x.id)}>Bilgiyi aç</button></article>)}</div>}{!item&&<details className="tp-knowledge-sources"><summary>Hastalık sözlüğü ({labels.length})</summary><p>PlantVillage sınıf adları yalnızca arama ve sınıflandırma sözlüğüdür; teşhis veya mücadele talimatı değildir.</p>{labels.map(e=><article key={e.id}><h2>{e.titleTr}</h2><p>{e.crops.join(' · ')}</p></article>)}</details>}{!item&&<details className="tp-knowledge-sources"><summary>Kaynaklar ve lisans bilgisi</summary>{knowledgeSources.map(s=><article key={s.id}><h2>{s.name}</h2><p>{s.description}</p><small>{s.license} · Kaynak kontrolü: {s.checkedAt}</small></article>)}</details>}</section>}
