from __future__ import annotations

ENGINE_REGISTRY = {
    "sl2p": {
        "role": "sentinel2_biophysical_traits",
        "rollout": "pilot",
        "upstream": "djamainajib/SL2P-SL2PCCRS_PYTHON",
        "upstream_commit": "71ac9e0453a58610d73283fb6a1ad15e19dbae89",
        "license": "MIT + Crown Copyright notice (upstream License)",
        "adapter_version": 1,
        "production_authority": False,
        "diagnostic_authority": False,
        "input_authority": "server-derived-only",
        "collection": "Sentinel-2 L2A",
        "spatial_resolution_m": 20,
        "variables": ["LAI", "fCOVER", "fAPAR", "CCC", "CWC", "Albedo"],
        "quality_outputs": ["networkID", "model_error", "QC_input", "QC_output"],
        "algorithm": "SL2P-V0",
        "sl2pccrs_gate": "requires verified land-cover partition before enablement",
    },
    "rscm": {
        "role": "remote_sensing_crop_model_assimilation_bridge",
        "rollout": "shadow",
        "upstream": "RS-iCM/RSCM",
        "upstream_commit": "7c48c6c93d758c72aceb99e9923181a77b7c51cb",
        "license": "MIT",
        "adapter_version": 1,
        "production_authority": False,
        "yield_authority": False,
        "prescription_authority": False,
        "input_authority": "server-derived-only",
        "supported_crops": ["wheat", "maize", "rice"],
        "assimilation_signal": "SL2P LAI",
        "calendar_scope": "planting-relative day axis; supports seasons crossing calendar-year boundaries",
        "note": "Calibrates crop-model parameters against real satellite LAI evidence; no farmer-facing yield/prescription authority.",
    },
    "unicrop": {
        "role": "data_harmonization_quality_provenance",
        "rollout": "pilot",
        "upstream": "CoDIS-Lab/UniCrop",
        "license": "MIT",
        "adapter_version": 1,
        "production_authority": False,
        "yield_authority": False,
        "input_authority": "server-derived-only",
        "implementation": "TarlaPusula native quality/provenance adapter inspired by UniCrop pipeline design",
        "source_categories": ["satellite", "weather", "soil", "management", "terrain", "model"],
        "note": "No UniCrop yield model is treated as an authority; only harmonization, provenance and data-confidence concepts are integrated.",
    },
    "pyfao56": {
        "role": "irrigation_water_balance",
        "rollout": "shadow",
        "upstream": "kthorp/pyfao56",
        "upstream_commit": "1d242ee985be0edbc4946f06e7e94a487d4bc0c9",
        "package": "pyfao56==1.4.3",
        "license": "CC0-1.0 / public domain dedication",
        "adapter_version": 1,
        "production_authority": False,
    },
    "pcse": {
        "role": "crop_phenology_growth",
        "rollout": "pilot",
        "upstream": "ajwdewit/pcse",
        "upstream_commit": "0d51ae84f405fd9b061222f2a0130e5351f460df",
        "package": "pcse==6.0.13",
        "license": "EUPL-1.1-or-later (upstream LICENSE)",
        "adapter_version": 2,
        "production_authority": False,
        "pilot_model": "Wofost72_PP",
        "water_stress_authority": False,
    },
    "aquacrop": {
        "role": "seasonal_irrigation_yield_scenarios",
        "rollout": "pilot",
        "upstream": "aquacropos/aquacrop",
        "upstream_commit": "36cc20e44644ed1704398889312435c85e04a2f3",
        "package": "aquacrop==3.1.0",
        "license": "Apache-2.0 (upstream LICENSE)",
        "adapter_version": 2,
        "production_authority": False,
    },
    "cropforge": {
        "role": "crop_digital_twin_weather_growth_shadow",
        "rollout": "shadow",
        "upstream": "saswatsundar123/CropForge",
        "upstream_release": "v1.0.1",
        "package": "cropforge==1.0.1",
        "license": "MIT",
        "adapter_version": 2,
        "production_authority": False,
        "yield_authority": False,
        "irrigation_prescription_authority": False,
        "nutrient_prescription_authority": False,
        "execution_enabled": True,
        "input_authority": "server-derived-only",
        "supported_crops": ["wheat", "maize"],
        "runtime_scope": "observed weather + first-party crop plugin only; soil-water, nutrients, terrain, erosion and management physics remain gated",
        "candidate_features": [
            "crop_growth_scenario",
            "fao56_et0_cross_check",
            "terrain_erosion_scenario",
            "multi_season_rotation",
        ],
        "note": "Phase 2 executes the real CropForge v1.0.1 crop/weather core in shadow mode only. Output has no production, yield or prescription authority.",
    },
    "dssat": {
        "role": "whole_season_management_shadow",
        "rollout": "shadow",
        "upstream": "DSSAT/dssat-csm-os",
        "upstream_release": "v4.8.6.0",
        "license": "BSD-3-Clause",
        "adapter_version": 2,
        "production_authority": False,
        "yield_authority": False,
        "irrigation_prescription_authority": False,
        "nutrient_prescription_authority": False,
        "execution_gate": "server_prepared_bundle_plus_verified_cultivar_mapping",
        "input_authority": "server-prepared-bundle-only",
        "supported_scope": "season-scale prepared shadow evidence; no farmer-facing prescription",
        "runtime": "official DSSAT-CSM v4.8.6.0 Linux binary built from release tag",
        "run_mode": "B",
        "bundle_contract_version": 1,
    },
    "plantcv": {
        "role": "quantitative_photo_phenotyping",
        "rollout": "pilot",
        "upstream": "danforthcenter/plantcv",
        "upstream_commit": "2b587bc08a957084d209f33dcfeefb33021eb4c9",
        "package": "plantcv==4.11.3",
        "license": "MPL-2.0",
        "adapter_version": 1,
        "production_authority": False,
        "diagnostic_authority": False,
        "input_contract": "server_derived_activity_photo_v1",
        "output_contract": "photo_phenotyping_evidence_v1",
        "measurements": [
            "area_px",
            "convex_hull_area_px",
            "solidity",
            "perimeter_px",
            "width_px",
            "height_px",
            "longest_path_px",
            "hue_circular_mean",
            "hue_circular_std",
            "hue_median",
            "saturation_mean",
            "saturation_median",
            "value_mean",
            "value_median",
        ],
        "segmentation": "TarlaPusula HSV + excess-green conservative mask before PlantCV analysis",
        "diagnosis_policy": "never infer disease/pest from PlantCV color or shape metrics alone",
    },
    "plantvillage-shadow": {
        "role": "independent_leaf_disease_shadow_classification",
        "rollout": "shadow",
        "upstream": "imaflower/plantvillage-mobilenetv3",
        "source": "Hugging Face",
        "source_revision": "main",
        "license": "MIT",
        "runtime": "onnxruntime-cpu",
        "training_dataset": "PlantVillage",
        "adapter_version": 1,
        "production_authority": False,
        "diagnostic_authority": False,
        "confidence_authority": False,
        "input_contract": "server_derived_activity_photo_v1",
        "output_contract": "plantvillage_closed_set_shadow_v1",
        "crop_guard": True,
        "domain_shift_guard": "curated PlantVillage leaf photos are not treated as field-domain validation",
        "diagnosis_policy": "top-k scores are independent shadow evidence only; never prescribe or raise confidence alone",
    },
    "agrifm": {
        "role": "multisource_temporal_agriculture_mapping",
        "rollout": "off",
        "upstream": "flyakon/AgriFM",
        "upstream_commit": "13f476e2d5b698387fa8ce068e793cc1c33f8279",
        "license": "Apache-2.0 (upstream LICENSE)",
        "adapter_version": 0,
        "production_authority": False,
        "supported_sources": ["Sentinel-2", "Landsat-8/9", "MODIS"],
        "candidate_tasks": ["cropland_mapping", "field_boundary", "early_season_crop_mapping", "specific_crop_mapping"],
        "input_contract": "sentinel2_l2a_temporal_cube_v1",
        "cube_schema_version": 1,
        "pixel_dtype": "float32",
        "reflectance_scale": "unitless_0_1",
        "reflectance_range": [0, 1],
        "invalid_reflectance_policy": "reject_unmasked_out_of_range",
        "input_authority": "server_derived_only",
        "minimum_observations": 4,
        "minimum_valid_pixel_fraction": 0.10,
        "maximum_selected_observations": 12,
        "selection_policy": "latest_eligible_unique_acquisitions",
        "observation_identity": "stac_item_id_plus_acquisition_time",
        "provenance_required": ["stac_item_id", "acquired_at", "collection", "provider"],
        "maximum_scene_cloud_cover_percent": 30,
        "required_bands": ["B02", "B03", "B04", "B08"],
        "cloud_mask_source": "Sentinel-2 L2A SCL",
        "scl_rejected_classes": [0, 1, 3, 8, 9, 10, 11],
        "temporal_order": "ascending_acquisition_time",
        "duplicate_acquisition_policy": "reject",
        "spatial_alignment": "common_10m_grid",
        "cube_shape_policy": "fixed_64x64_field_bbox",
        "cube_width": 64,
        "cube_height": 64,
        "maximum_cube_bytes": 8388608,
        "maximum_total_evidence_bytes": 33554432,
        "maximum_decoded_tensor_bytes": 786432,
        "oversized_cube_policy": "reject",
        "resampling_policy": "explicit_per_band_required",
        "missing_pixel_policy": "mask_not_zero_fill",
        "cube_fingerprint_required": True,
        "fingerprint_algorithm": "SHA-256",
        "fingerprint_scope": "pixels_mask_dates_scene_ids_geometry_contract",
    },
    "autogeobound": {
        "role": "automatic_field_boundary_research",
        "rollout": "off",
        "upstream": "agstack/autogeobound",
        "upstream_commit": "7087b59e51438ec370b698186805751be9296ec2",
        "license": "Apache-2.0",
        "adapter_version": 0,
        "production_authority": False,
    },
    "openagri-pest-disease": {
        "role": "pest_disease_risk_benchmark",
        "rollout": "off",
        "upstream": "agstack/OpenAgri-PestAndDiseaseManagement",
        "upstream_commit": "3aa67a9ad3de6ff8a772dc635db041ec53845aa4",
        "license": "EUPL-1.2",
        "adapter_version": 0,
        "production_authority": False,
    },
    "agml": {
        "role": "disease_vision_research",
        "rollout": "off",
        "upstream": "Project-AgML/AgML",
        "upstream_commit": "c3343fc3b3f8abd89983927da3fc8319cb019d49",
        "license": "Apache-2.0",
        "adapter_version": 0,
        "production_authority": False,
    },
    "farmvibes-ai": {
        "role": "geospatial_pipeline_reference",
        "rollout": "off",
        "upstream": "microsoft/farmvibes-ai",
        "upstream_commit": "d10670e18742d05aec50f73e4695d47978908994",
        "license": "MIT",
        "adapter_version": 0,
        "production_authority": False,
    },
}
