import { useEffect, useState } from 'react';
import type { IrrigationDecisionResult } from '../../irrigation/types/irrigationDecision';
import { loadIrrigationEconomicsSnapshot, saveIrrigationEconomicsProfile } from '../services/irrigationEconomics.service';
import type { IrrigationEconomicsSnapshot } from '../types/irrigationEconomics';
function n(v:string){if(!v.trim())return null;const x=Number(v);return Number.isFinite(x)?x:null}
export default function IrrigationEconomicsPanel({fieldId,decision}:{fieldId:string;decision:IrrigationDecisionResult}){
 const [snapshot,setSnapshot]=useState<IrrigationEconomicsSnapshot|null>(null);const [eff,setEff]=useState('');const [power,setPower]=useState('');const [flow,setFlow]=useState('');const [price,setPrice]=useState('');const [message,setMessage]=useState('');
 const refresh=async()=>{const s=await loadIrrigationEconomicsSnapshot(fieldId,decision);setSnapshot(s);setEff(s.profile.irrigationEfficiencyPct?.toString()??'');setPower(s.profile.pumpPowerKw?.toString()??'');setFlow(s.profile.pumpFlowM3Hour?.toString()??'');setPrice(s.profile.energyPriceTryKwh?.toString()??'')}; useEffect(()=>{void refresh()},[fieldId,decision.generatedAt]);
 return <div className="tp-irrigation-detail-model"><small>SULAMA EKONOMİSİ · MADDE 19</small><div className="tp-irrigation-detail-model-row"><span>Brüt su</span><strong>{snapshot?.recommended.totalGrossWaterM3!=null?`${snapshot.recommended.totalGrossWaterM3.toLocaleString('tr-TR')} m³`:'Profil gerekli'}</strong></div><div className="tp-irrigation-detail-model-row"><span>Enerji / maliyet</span><strong>{snapshot?.recommended.energyKwh!=null?`${snapshot.recommended.energyKwh.toLocaleString('tr-TR')} kWh · ${snapshot.recommended.energyCostTry?.toLocaleString('tr-TR')} TL`:'Hesaplanamadı'}</strong></div><div className="tp-irrigation-detail-model-row"><span>Sezon su verimliliği</span><strong>{snapshot?.season.waterProductivityKgM3!=null?`${snapshot.season.waterProductivityKgM3} kg/m³`:'Gerçek hasat + su kaydı gerekli'}</strong></div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:6,marginTop:10}}><input style={{background:'#050505',color:'#fff',border:'1px solid rgba(255,255,255,.15)',borderRadius:8,padding:8}} placeholder="Randıman %" value={eff} onChange={e=>setEff(e.target.value)}/><input style={{background:'#050505',color:'#fff',border:'1px solid rgba(255,255,255,.15)',borderRadius:8,padding:8}} placeholder="Pompa kW" value={power} onChange={e=>setPower(e.target.value)}/><input style={{background:'#050505',color:'#fff',border:'1px solid rgba(255,255,255,.15)',borderRadius:8,padding:8}} placeholder="Debi m³/saat" value={flow} onChange={e=>setFlow(e.target.value)}/><input style={{background:'#050505',color:'#fff',border:'1px solid rgba(255,255,255,.15)',borderRadius:8,padding:8}} placeholder="TL/kWh" value={price} onChange={e=>setPrice(e.target.value)}/></div><button style={{marginTop:8}} onClick={async()=>{try{await saveIrrigationEconomicsProfile(fieldId,{irrigationEfficiencyPct:n(eff),pumpPowerKw:n(power),pumpFlowM3Hour:n(flow),energyPriceTryKwh:n(price),cropPriceTryKg:null});await refresh();setMessage('Profil kaydedildi.')}catch(e){setMessage(e instanceof Error?e.message:'Kaydedilemedi.')}}}>Pompa profilini kaydet</button><p>Ekonomik fayda (gelir artışı) doğrulanmış tarla-özel verim-cevap modeli olmadan hesaplanmaz. {message}</p></div>
}
